[package]
name = "aof2022"
version = "0.1.0"
edition = "2021"

[lib]
name = "aoc2022"
path = "src/lib.rs"

[[bin]]
name = "aoc2022-runner"
path = "src/bin.rs"

[dependencies]
argparse = "0.2.2"
itertools = "0.11.0"
queues = "1.1.0"
regex = "1.8.4"
